### ISSUE TITLE
How to wrap LV2/VST plugins with Carla, yabridge, LinVst

### ISSUE THREAD

**Issue by westurner** [BespokeSynth/BespokeSynth#1614]
## Summary

What are good ways to wrap LV2 / VST plugins with Carla, yabridge, LinVst and Linux?

- VST plugins can be:
  - 32bit or 64bit
  - compiled for: Win/Lin  (mac: AudioUnit)
  - ENH: Display these plugin attrs somehow in the Plugin Manager
- "Yabridge vs. LinVst vs. Carla vs. WineASIO "
  https://www.reddit.com/r/linuxaudio/comments/12orpak/yabridge_vs_linvst_vs_carla_vs_wineasio/
  - yabridge: https://github.com/robbert-vdh/yabridge
    > Yabridge seamlessly supports using both 32-bit and 64-bit Windows VST2, VST3, and CLAP plugins in 64-bit Linux plugin hosts as if they were native plugins,
    > with optional support for plugin groups to enable inter-plugin communication for VST2 plugins and quick startup times. Its modern concurrent architecture and focus on transparency allows yabridge to be both fast and highly compatible, while also staying easy to debug and maintain.
  - Carla: https://github.com/falkTX/Carla
    > - LADSPA, DSSI, LV2 and VST2, VST3 and AU plugin formats
    > - SF2/3 and SFZ sound banks
    > Experimental:
    > - Export any Carla loadable plugin or sound bank as an LV2 plugin
    > - Plugin bridge support (such as running 32bit plugins on a 64bit Carla, or Windows plugins on Linux)
  - LinVst: https://github.com/osxmidi/LinVst
    > - LinVst adds support for Windows vst's to be used in Linux vst capable DAW's.
    > - See LinVst-X for running vst plugins in a single Wine process so that plugins can communicate with each other or plugins that can use shared samples between instances will be able to communicate with their other instances.
    > - See LinVst3 https://github.com/osxmidi/LinVst3 for running vst3 plugins.
  - LinVstT-X: https://github.com/osxmidi/LinVst-X 
    > LinVst-X runs vst plugins in a single Wine process so plugins that communicate with each other or plugins that can use shared samples between instances will be able to communicate with their other instances.
    > - Plugin instances can communicate with each other (which is not possible with LinVst), for example,
    > - Plugins running in one process are not sandboxed, so if one plugin crashes then the whole lot might crash.
    > - It's best to use plugins that already run with LinVst and/or use TestVst to test how a plugin might run under Wine.
  - LinVst3: https://github.com/osxmidi/LinVst3
    > - For 64 bit vst3's only.
  - WineASIO: https://github.com/wineasio/wineasio
    > [Windows ASIO] to JACK driver for WINE 

### Motivation

What use cases would this feature improve?

- [ ] DOC: Docs for users on how to get more of their LV2, VST, VST3 plugins working
  - Settings > `plugin_preference_order`:
    default: `VST3;VST;AudioUnit;LV2`
- Here's a test set of many plugins and their github source urls:
  https://audinux.github.io/packages/index.html 
  https://copr.fedorainfracloud.org/coprs/ycollet/audinux and also
- And other open source patchbay and filter / transform composition apps:
  - https://github.com/Houston4444/HoustonPatchbay
    > This a patchbay for JACK used by RaySession and Patchance, usable by other python Qt5 softwares.
    - RaySession: https://github.com/Houston4444/RaySession looks cool, is a patchbay for JACK
    - Patchance: https://github.com/Houston4444/Patchance ; JACK patchbay gui w/ ALSA MIDI
      > - It is a direct alternative to Catia or Patchage
      > - Prevent the boxes from overlapping
      > - Search a box with a pattern
  - org.pipewire.helvum: https://gitlab.freedesktop.org/pipewire/helvum https://flathub.org/apps/org.pipewire.Helvum
    > Helvum is a GTK-based patchbay for pipewire, inspired by the JACK tool [catia](https://kx.studio/Applications:Catia).
  - easyeffects: https://github.com/wwmm/easyeffects ; pipewire + GStreamer -> just pipewire filters
- ENH: Parametric EQ w/ Input waveform vis + Output waveform vis
- MIDI
 - [x] notecanvas : https://www.bespokesynth.com/docs/index.html#notecanvas
 - [x] notesequencer : https://www.bespokesynth.com/docs/index.html#notesequencer
   - otherwise a plugin is necessary
   - https://github.com/BespokeSynth/BespokeSynth/issues/1608 [...] e.g. MuseScore
  - looks like Arch already has a muse-sounds-manager package
    - "Is there any other app that can play the .spx or .sts files that Muse uses?" [now in addition to SFX sound fonts]
      https://www.reddit.com/r/Musescore/comments/znz2zb/is_there_any_other_app_that_can_play_the_spx_or/ ; `libMuseSamplerCoreLib.so`
      - https://github.com/musescore/MuseScore/blob/master/share/plugins/note_names/notenames.qml#L185
- [ ] Wrap Bespokesynth itself as an LV2/VST2/VST3 plugin

**Comment by maxigaz** [comment]
Technically, you can already load Carla as a plugin. However, in my experience (with Bespoke Nightly and Carla 2.5.8, running on Arch Linux and Sway), it is practically unusable:

- The UI of the LV2 version of Carla doesn't appear at all. (An empty window is shown.)
- The UI of the VST2 version can't be resized (or rather it can be, but it frequently shifts back to its original window size). What's even more troublesome is that after adding a couple of plugins inside Carla and playing some audio with them, the UI of both Carla and the plugins hosted by it become extremely sluggish; they are updated at 1-2 frames per second.

For me, the biggest advantage of having Carla in BespokeSynth would be to compensate for Bespoke's lack of multi-channel support in plugins. (So, for example, I could load a drumkit as a single plugin and mix its audio outputs without any restriction.)

**Comment by NoxyNixie** [comment]
I'm a bit confused on what the actual feature request is, can you clarify / elaborate? Or is this more a question (if so I'm also unclear on what the question is)?

**Comment by westurner** [comment]
> How to wrap VST plugins with Carla, yabridge, LinVst with Linux

This is a question or an RFC. Specifically, almost none of the plugins in
the Fedora or Audinux package repos - for example - work, on this 64bit
Linux machine.

Plugins themselves are not Bespokesynth devs' responsibility. The new
loader looks nice, but still I'm like 5/50 here.

I think there's a way to integrate Carla or yabridge and get most plugins
working on Linux,
because the other says other Linux DAWs like Bitwig and Reaper handle most
VST/LV2 plugins.

- Could there be a column for plug-in attrs in the plug-in loader; type,
original platform, 32/64bit
- Are there other apps with native Carla or Yabridge integration?

- Any experience with Yabridge?
- What's a good way to get Bespokesynth to not directly load plugins
because they have to be wrapped w/ Carla/yabridge to work?

**Comment by maxigaz** [comment]
> almost none of the plugins in the Fedora or Audinux package repos - for example - work, on this 64bit Linux machine.

Could you be more specific? What plugins can you confirm as not working and which ones as working?

**Comment by westurner** [comment]
With this Dockerfile (and distrobox), only "Rubber Band" loads in Bespokesynth. I shcould just use another distro.

<details><summary>screenshots, dockerfile</summary>

![bespokesynth_plgins](https://github.com/BespokeSynth/BespokeSynth/assets/50891/78f685c1-4710-4d3b-91ec-fb9e50e1d758)
![bespokesynth_plugins__Plugin_Manager](https://github.com/BespokeSynth/BespokeSynth/assets/50891/47457d16-7802-46fa-828e-2b5fe3b720b4)
![Screenshot from 2024-07-11 15-22-46](https://github.com/BespokeSynth/BespokeSynth/assets/50891/ed7cd254-3b40-4ecd-a7ad-f0822c7c0bff)


```Dockerfile

FROM registry.fedoraproject.org/fedora-toolbox:40

LABEL name="westurner/music" \
    version="0.0.1" \
    maintainer="@westurner" \
    summary="A fedora container with music tools. References: Fedora Jam pkgs, dnf search, audinux, fedora forums" \
    usage="distrobox create -i westurner/music -n music && distrobox enter music" \

# TODO: for debugging with rr: Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.d/10-rr.conf.


RUN dnf -y install dnf-plugins-core bash-completion diffutils git dnf-plugins-core \
        pipewire-utils \
        podman-remote \
        \
        vmpk \
        audacity \
        ardour8 \
        \
        python3-pip \
        python3-setuptools \
        python3-ipython \
        python3-ipdb \
        python3-pytest \
        python3-pytest-cov \
        python3-virtualenvwrapper \
        tox \
        \
        rust \
        cargo \
        \
        rr \
        gdb


RUN dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf -y swap ffmpeg-free ffmpeg --allowerasing


# dnf search vst
# dnf search lv2
# dnf search lv2-* | pyline 'l.split(".")[0] + " \\"' | pbcopy

RUN dnf -y copr enable ycollet/audinux && \
    dnf repoquery --whatrequires Carla && \
    dnf -y swap Carla Carla-mao && \
    dnf -y swap Carla-vst vst-Carla-mao && \
    dnf -y swap lv2-carla lv2-Carla-mao && \
    dnf -y install \
        BespokeSynth \
        Carla-mao \
        vst-Carla-mao \
        lv2-Carla-mao \
        \
        konfyt \
        lv2-x42-plugins \
        lsp-plugins \
        lsp-plugins-vst3 \
        vst-amsynth-plugin \
        zynaddsubfx-vst \
        lv2-mdaEPiano \
        lv2-mdala-plugins \
        \
        lv2-abGate \
        lv2-amsynth-plugin \
        lv2-bankstown \
        lv2-c++-tools \
        lv2-c++-tools \
        lv2-c++-tools-devel \
        lv2-c++-tools-devel \
        lv2-calf-plugins \
        lv2-calf-plugins-gui \
        lv2-devel \
        lv2-devel \
        lv2-doc \
        lv2-drumkv1 \
        lv2-eq10q \
        lv2-example-plugins \
        lv2-fabla \
        lv2-guitarix-plugins \
        lv2-ir-plugins \
        lv2-ll-plugins \
        lv2-mdaEPiano \
        lv2-mdala-plugins \
        lv2-newtonator \
        lv2-padthv1 \
        lv2-qmidiarp \
        lv2-samplv1 \
        lv2-setBfree-plugins \
        lv2-sorcer \
        lv2-swh-plugins \
        lv2-synthv1 \
        lv2-vocoder-plugins \
        lv2-x42-plugins \
        lv2-zam-plugins \
        lv2-zynadd-plugins \
        \
        jalv \
        jalv_select \
        ladspa-zam-plugins \
        lilv \
        sratom \
        suil \
        zam-plugins \
        \
        \
        Rack-v1 \
        Rack-v2 \
        chordv \
        hydrogen \
        hydrogen-drumkits-2 \
        ladspa-guitarsynth \
        ladspa-noise-suppression-for-voice \
        ladspa-vocoder \
        lv2-showdmidi \
        lv2-vocoder \
        midivisualizer \
        qjackctl \
        repitch.lv2 \
        roomreverb \
        string-machine \
        string-machine \
        surge-xt \
        vst-ykchorus \
        vst3-drops \
        vst3-melodrumatic \
        vst3-roomreverb \
        vst3-surge-xt \
        xjadeo \
        \
        chuck \
        lives-mao \
        \
        rosegarden4 \
        tuxguitar \
        musescore \
        pianobooster \

        # LinVst3 yabridge \
        lmms-mao-weekly

        # lsp-plugins-vst \ # --exclude=Carla

RUN dnf -y install https://muse-cdn.com/Muse_Sounds_Manager_Beta.rpm

RUN dnf -y copr enable alextee/zrythm && \
    dnf -y install zrythm


RUN dnf -y install flatpak fedora-flathub-remote && \
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    flatpak install -y --app org.pipewire.Helvum && \
    flatpak install -y --app org.zrythm.Zrythm

RUN dnf -y install adwaita-qt5 adwaita-qt6 qt5ct

USER 1000:1000
WORKDIR /home/user

CMD /usr/bin/bash --login
```

</details>

**Comment by KottV** [comment]
It became more confusing and unrelated.

If you ask for howtos about bridges/wrappers - there is no any specific in Bespoke and Linux, just use them as in any other DAW. Or if you want to add such howtos into documentation = welcome.

If you're asking to change the plugins host part from JUCE to Carla - then I think it doesn't worth efforts, Carla has only the better LV2 support. And this change can break a lot for current projects and for Windows/Mac, where the Carla is not well tested.

According not working plugins in Fedora with Audinux repo - it looks like Fedora with Audinux repo problem only.

**Comment by NoxyNixie** [comment]
Alright well I'm not sure where this feature request is going but I can tell you that Surge XT for sure works in Bespoke on most Linux distros. If you are unable to do so you may have a problem in your setup / distro.

Carla will likely not be integrated into Bespoke as Bespoke heavily relies on JUCE already and JUCE already gives us the ability to load VST3 VST AudioUnit and LV2 plugins (provided they are 64bit). There are plans to also support Clap in the future. There are no plans to do plugin sandboxing (which would allow for supporting 32bit plugins).

For the rest of the things you mention in this feature request; it is all over the place. Some of the things mentioned should be their own issues not a big list like we have in this issue.

For the time being I'm closing this issue. The things in here seem more like a thing that should be discussed in the [Bespoke discord](https://discord.gg/cSpKKWvmgQ) in [#linux-discussion](https://discord.com/channels/846834873254805554/890204485153091646) or [#nerdy-stuff](https://discord.com/channels/846834873254805554/867541544705196032).

**Comment by westurner** [comment]
- Some of the plugins that aren't loading are from the Fedora package
repos, not Audinux
- Same issue in the container (with distrobox) as on the fedora host
- Audacity loads that greater subset of all of the plugin packages matching
LV2 and VST in those repos. I haven't yet tried with ardour, or those the
other patchbay interfaces that could respawn bespoke with cli args as a
plugin when it crashes.

To get other plugins working in addition to "Rubber band":

- [ ] generate external configuration of Yabridge or Carla for each plugin
which must be wrapped
- [ ] add each wrapped plug-in instance to a directory
- [ ] reload plugins with wrapped plugins masked out


- I agree that there are multiple issues
- Hopefully there's a simple fix to get plugins working stably without
sandboxing on fc40 Fedora 40
